### PR TITLE
Shizhao zheng1

### PR DESCRIPTION
**Pull request by ElonZhengUofT**
Some updates in Favorites entity

### CODE REVIEW

**Comment by hzhqwq** [comment]
good

**Comment by Felixzhangmingzhe** [comment]
Great job!

**Review by hzhqwq — APPROVED** [review]

**Comment by KeepZoneqp** [comment]
good

**Comment by ElonZhengUofT** [comment]
good

**Review by KeepZoneqp — APPROVED** [review]
good

**Review by Felixzhangmingzhe — APPROVED** [review]

**Review by Felixzhangmingzhe — APPROVED** [review]

**Review by Felixzhangmingzhe — APPROVED** [review]

**Pull request merged**
